### ISSUE TITLE
Run main_policy.py problem

### ISSUE THREAD

**Issue by 945716994** [wangzizhao/CausalDynamicsLearning#1]
when i run the file, i got a problem:
Unable to load module hid, required to interface with SpaceMouse.

           Only macOS is officially supported. Install the additional

           requirements with `pip install -r requirements-extra.txt`
Traceback (most recent call last):
  File "main_policy.py", line 9, in <module>
    from model.inference_mlp import InferenceMLP
  File "/home/wjg/code/CausalDynamicsLearning/cdl/model/inference_mlp.py", line 8, in <module>
    from model.inference import Inference
  File "/home/wjg/code/CausalDynamicsLearning/cdl/model/inference.py", line 14, in <module>
    from utils.utils import to_numpy, preprocess_obs, postprocess_obs
  File "/home/wjg/code/CausalDynamicsLearning/cdl/utils/utils.py", line 11, in <module>
    from env.physical_env import Physical

**Comment by wangzizhao** [comment]
I guess that's not the full traceback. If I remember correctly, the hid is required for robosuite, and robosuite is only needed for the manipulation environment.
Hence, to run the manipulation environment, it's required to install robosuite which AFAIK only supports Linux.
To run chemical environment only, you can comment out all `import from robosuite`.

**Comment by 945716994** [comment]
I already intsall the robosuit on the Linux server. 
i have a question that the env.physical_env come from robosuite or it just a python file?

**Comment by wangzizhao** [comment]
I just pushed them to `cdl/env`. This directory somehow is ignored by .gitignore and I didn't notice it. Thanks for the reminder!
